# Generated by Django 2.0.5 on 2018-05-20 16:59

from django.db import migrations, models


def create_initial_site_settings(apps, schema_editor):

    SiteSettings = apps.get_model('datracker', 'SiteSettings')

    if not SiteSettings.objects.exists():
        SiteSettings.objects.create(
            site_name='DaTracker', site_slogan='Track everything'
        )

def reverse_initial_site_settings(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('datracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150)),
                ('site_slogan', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_initial_site_settings, reverse_initial_site_settings),
    ]
