# Generated by Django 2.0.5 on 2018-05-21 00:32

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datracker', '0002_create_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(default='', help_text='Main title displayed on top of each page', max_length=150)),
                ('label', models.CharField(default='', help_text='Is displayed for example in navbar or links', max_length=150)),
                ('meta_title', models.CharField(default='', help_text='Title used only for social networks and search engines.', max_length=150)),
                ('meta_description', models.TextField(default='', help_text='Description used only for social networks and search engines.', max_length=200)),
                ('content', models.TextField(default='')),
                ('slug', models.SlugField(help_text='Specifies name of page in URL address.', unique=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
