# Generated by Django 2.0.5 on 2018-05-21 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datracker', '0003_create_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(default='', help_text='Category name', max_length=150)),
                ('description', models.TextField(default='', help_text='Larger descriptive text about Issue', max_length=800)),
                ('solved', models.DateTimeField(help_text='Indicates when issue was solved.', null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('close_issue', 'Can close unfinished issue assigned to self'),),
            },
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(default='', help_text='Category name', max_length=150)),
                ('description', models.TextField(default='', help_text='Larger descriptive text about category.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Issue Categories',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datracker.IssueCategory'),
        ),
    ]
