# Generated by Django 2.0.5 on 2018-05-26 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datracker', '0004_create_issues_and_issue_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': (('update_solved_time', 'Can update solved time if issues upon creation or update'), ('close_issue', 'Can close unfinished issue assigned to self'))},
        ),
    ]
